# Generated by Django 3.1.2 on 2020-12-27 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Problem_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(default='', max_length=20)),
                ('number', models.IntegerField(default=0)),
                ('page', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.section')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=20)),
                ('page', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('problem_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.problem_group')),
            ],
        ),
    ]
