# Generated by Django 3.1.2 on 2021-01-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_problem_problem_group_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem_group',
            name='difficulty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='problem_group',
            name='number',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
