# Generated by Django 3.1.2 on 2021-01-01 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_similar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similar',
            name='fromProblem',
        ),
        migrations.AddField(
            model_name='similar',
            name='from_problem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_problem', to='app1.problem'),
        ),
        migrations.AddField(
            model_name='similar',
            name='to_problem',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_problem', to='app1.problem'),
        ),
    ]
