# Generated by Django 3.1.2 on 2021-01-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20210101_2131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Develop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='easy', to='app1.problem')),
                ('to_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='difficult', to='app1.problem')),
            ],
        ),
    ]
