# Generated by Django 3.1.2 on 2021-01-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct_flag',
            field=models.IntegerField(null=True),
        ),
    ]
