# Generated by Django 3.1.2 on 2021-01-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20210107_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectSituation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
