# Generated by Django 3.1.2 on 2021-01-07 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20210107_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='correct_flag',
            new_name='correct_situation',
        ),
    ]
