# Generated by Django 3.1.2 on 2021-01-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20210107_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='app1.answer'),
        ),
    ]
