# Generated by Django 3.1.2 on 2021-01-08 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_comment_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='origin_photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_photo', to='app1.photo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='photo', to='app1.photo'),
        ),
    ]
