# Generated by Django 3.1.2 on 2021-01-08 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_photo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
