# Generated by Django 3.1.2 on 2021-01-09 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_photo_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='updated_at',
        ),
    ]
