# Generated by Django 3.1.2 on 2021-01-09 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_auto_20210109_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='origin_photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_comment', to='app1.photo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reply_comment', to='app1.photo'),
        ),
    ]
