# Generated by Django 3.1.5 on 2021-01-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_by_evaluationtag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='by',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
