# Generated by Django 3.1.5 on 2021-01-21 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_bycomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CauseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, null=True)),
                ('cause_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause', to='app1.type')),
            ],
        ),
    ]
