# Generated by Django 3.1.5 on 2021-01-21 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0031_causetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='causetag',
            name='cause_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cause', to='app1.type'),
        ),
        migrations.CreateModel(
            name='With',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overcome_flag', models.BooleanField(null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.answer')),
                ('cause_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.causetag')),
                ('latest_with', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app1.with')),
                ('site_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
