# Generated by Django 3.1.5 on 2021-01-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20210122_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='with',
            name='latest_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app1.with'),
        ),
    ]
