# Generated by Django 3.1.5 on 2021-01-22 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_auto_20210122_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='with',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withes', to='app1.answer'),
        ),
    ]
