# Generated by Django 3.1.5 on 2021-01-22 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_auto_20210122_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='with',
            name='latest_with',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.latestwith'),
        ),
    ]
